import { describe,expect,it } from 'vitest'; import { amenityLabel,budgetTotal,directionsUrl,filteredResources,isStale,navigateDay,parseTripQuery,firstMomentIndexOfDay,stepMoment,advanceMoment,shouldSyncFromDay,zoomForMoment } from './trip'; import { itinerary } from '../data/itinerary'; import { resources } from '../data/resources'; import { simulationMoments } from '../data/simulation';
describe('trip helpers',()=>{it('adds budget ranges',()=>expect(budgetTotal([{min:2,max:3},{min:5,max:9}])).toEqual({min:7,max:12}));it('creates a driving link',()=>expect(directionsUrl('A','B',['C'])).toContain('travelmode=driving'));it('parses safe share parameters',()=>expect(parseTripQuery('?day=4&resource=green-bear')).toEqual({day:4,resource:'green-bear'}));it('filters day resources',()=>expect(filteredResources(resources,4).some(r=>r.id==='green-bear')).toBe(true));it('marks dated records stale',()=>expect(isStale('2025-01-01',90,new Date('2026-01-01'))).toBe(true));it('navigates within day bounds',()=>expect(navigateDay(itinerary,1,-1)).toBe(1));it('has no fake links for a missing source',()=>expect(resources.find(r=>r.id==='naluka')?.links.some(l=>l.kind==='official')).toBe(false));it('labels uncertainty honestly',()=>expect(amenityLabel('unknown')).toBe('Unknown'))});
describe('trip simulation player',()=>{
  const days=[1,1,1,2,2,3];
  it('finds the first moment index of a day',()=>{expect(firstMomentIndexOfDay(days,2)).toBe(3);expect(firstMomentIndexOfDay(days,1)).toBe(0)});
  it('falls back to the start for an unknown day',()=>expect(firstMomentIndexOfDay(days,9)).toBe(0));
  it('steps by one moment without leaving the timeline',()=>{expect(stepMoment(6,3,-1)).toBe(2);expect(stepMoment(6,0,-1)).toBe(0);expect(stepMoment(6,5,1)).toBe(5)});
  it('advances during playback and loops back to the start at the end',()=>{expect(advanceMoment(6,4)).toBe(5);expect(advanceMoment(6,5)).toBe(0)});
  it('resyncs only on a genuine external day change, not the player echo',()=>{expect(shouldSyncFromDay(7,2)).toBe(true);expect(shouldSyncFromDay(2,2)).toBe(false)});
  it('zooms tight on places and pulls back on borders and long drives',()=>{expect(zoomForMoment('border')).toBeLessThan(zoomForMoment('start'));expect(zoomForMoment('start')).toBeLessThan(zoomForMoment('arrive'));expect(zoomForMoment('drive')).toBe(zoomForMoment('border'));expect(zoomForMoment('arrive')).toBe(zoomForMoment('sleep'))});
  it('gives every simulation moment a coordinate on the map',()=>{expect(simulationMoments.every(m=>Array.isArray(m.coordinates)&&m.coordinates.length===2&&m.coordinates.every(n=>Number.isFinite(n)))).toBe(true)});
});
