import { writeFile } from 'node:fs/promises';
// Bakes real driving geometry into src/data/routeGeometry.ts once, so the site stays static (no runtime routing API).
// Coordinates are [longitude, latitude]. Re-run with `npm run build:routes` if the itinerary endpoints change.
// Days 1-3, 5-10 are efficient origin -> destination drives; Day 4 is a Tara base-day loop through its stops.
const OSRM = 'https://router.project-osrm.org/route/v1/driving';
const days = [
  { day: 1, points: [[26.10, 44.43], [22.32, 44.68]] },
  { day: 2, points: [[22.32, 44.68], [21.68, 44.66]] },
  { day: 3, points: [[21.68, 44.66], [19.56, 43.93]] },
  { day: 4, points: [[19.56, 43.93], [19.50, 43.98], [19.39, 43.87], [19.55, 43.92], [19.56, 43.93]] },
  { day: 5, points: [[19.56, 43.93], [18.70, 43.35]] },
  { day: 6, points: [[18.70, 43.35], [17.90, 43.26]] },
  { day: 7, points: [[17.90, 43.26], [18.65, 42.49]] },
  { day: 8, points: [[18.65, 42.49], [19.51, 42.18]] },
  { day: 9, points: [[19.51, 42.18], [19.98, 40.02]] },
  { day: 10, points: [[19.98, 40.02], [20.85, 39.67]] },
];
const round = (n) => Math.round(n * 1e5) / 1e5;
const fetchLeg = async ({ day, points }) => {
  const coords = points.map((p) => p.join(',')).join(';');
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), 20000);
  try {
    const res = await fetch(`${OSRM}/${coords}?overview=simplified&geometries=geojson`, { signal: ctl.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (data.code !== 'Ok' || !data.routes?.[0]) throw new Error(data.code || 'no route');
    const line = data.routes[0].geometry.coordinates.map(([lng, lat]) => [round(lng), round(lat)]);
    const km = Math.round(data.routes[0].distance / 1000);
    console.log(`Day ${day}: ${line.length} points, ~${km} km`);
    return [day, line];
  } catch (e) {
    console.warn(`Day ${day}: FAILED (${e.message}) — will fall back to the straight line`);
    return [day, null];
  } finally { clearTimeout(timer); }
};
console.log('Fetching driving geometry from OSRM…');
const results = [];
for (const d of days) { results.push(await fetchLeg(d)); await new Promise((r) => setTimeout(r, 400)); }
const entries = results.filter(([, line]) => line).map(([day, line]) => `  ${day}: ${JSON.stringify(line)},`).join('\n');
const file = `// Generated by scripts/build-routes.mjs — do not edit by hand. Run \`npm run build:routes\` to refresh.\n// Real driving polylines [longitude, latitude] per day, baked so the site needs no runtime routing API.\n// Planning geometry only: a snapshot, not live road conditions. Verify closures and access before driving.\nexport const routeGeometry: Record<number, [number, number][]> = {\n${entries}\n};\n`;
await writeFile(new URL('../src/data/routeGeometry.ts', import.meta.url), file);
console.log(`\nWrote ${results.filter(([, l]) => l).length}/${days.length} day routes to src/data/routeGeometry.ts`);
